name: Issue closer.
description: Closing tickets that don't relate to the TDesktop repository.

inputs:
  token:
    required: true

runs:
  using: composite
  steps:
    - name: Download xml.
      shell: bash
      working-directory: ${{ github.action_path }}
      run: wget https://osx.telegram.org/updates/versions.xml || exit 0

    - name: Check a version from an issue.
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        npm init -y
        npm install compare-versions
        npm install fast-xml-parser
        npm install @actions/core
        npm install @actions/github
        node index.js ${{ inputs.token }}
